import React from 'react'
import Head from "next/head";
import InformationPage from '../../components/information/InformationPage'

const index = () => {
  return (  
    <>
      <Head>
        <title>Information - FAB BAG - Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://cdn.shopify.com/s/files/1/0052/7551/6995/files/LOGO_32x32.png?v=1548735766"
        />
      </Head>
      <InformationPage />
    </>
  )
}

export default index                                                                                                                                                                                                                                                      